### ISSUE TITLE
Class Cast Exception

### ISSUE THREAD

**Issue by malaverdiere** [secure-software-engineering/soot-infoflow#15]
I am getting this exception for some configurations of a given test case. 

    java.lang.ClassCastException: soot.RefType cannot be cast  to soot.ArrayType
    at soot.jimple.infoflow.problems.InfoflowProblem$1.addTaintViaStmt(InfoflowProblem.java:336)
    at soot.jimple.infoflow.problems.InfoflowProblem$1.access$500(InfoflowProblem.java:254)
    at soot.jimple.infoflow.problems.InfoflowProblem$1$2.createNewTaintOnAssignment(InfoflowProblem.java:692)
    at soot.jimple.infoflow.problems.InfoflowProblem$1$2.computeTargetsInternal(InfoflowProblem.java:487)
    at soot.jimple.infoflow.problems.InfoflowProblem$1$NotifyingNormalFlowFunction.computeTargets(InfoflowProblem.java:282)
    at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeNormalFlowFunction(InfoflowSolver.java:76)
    at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeNormalFlowFunction(InfoflowSolver.java:35)
    at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.processNormalFlow(IFDSSolver.java:437)
    at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.access$100(IFDSSolver.java:60)
    at soot.jimple.infoflow.solver.fastSolver.IFDSSolver$PathEdgeProcessingTask.run(IFDSSolver.java:607)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

**Comment by StevenArzt** [comment]
Since there has not been any further activity on this issue report for quite a while, I close it. If the problem persists, please open a new report.
